"""Fix camera event types

Revision ID: 411441e7dd6f
Revises: a33071ed69ba
Create Date: 2021-06-06 17:18:32.797851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411441e7dd6f'
down_revision = 'a33071ed69ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameraevent', sa.Column('annotated_image', sa.String(), nullable=True))
    op.add_column('cameraevent', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('cameraevent', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('cameraevent', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameraevent', sa.Column('data', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('cameraevent', 'status')
    op.drop_column('cameraevent', 'score')
    op.drop_column('cameraevent', 'annotated_image')
    # ### end Alembic commands ###
