"""Add camera resouse video URL

Revision ID: 431dfa9066a9
Revises: 2654520e8836
Create Date: 2021-06-07 19:37:23.447824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431dfa9066a9'
down_revision = '2654520e8836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('video_source_url', sa.String(), nullable=True))
    op.drop_column('camera', 'mock_resource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('mock_resource', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('camera', 'video_source_url')
    # ### end Alembic commands ###
