"""Add missing cols

Revision ID: a33071ed69ba
Revises: 1f88475f3c3a
Create Date: 2021-06-06 17:12:41.648447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33071ed69ba'
down_revision = '1f88475f3c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('alert', sa.Column('location_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'location_lng')
    op.drop_column('alert', 'location_lat')
    # ### end Alembic commands ###
