"""Largeblob col

Revision ID: bba7b899a323
Revises: a65a3a0c1931
Create Date: 2021-06-09 19:43:18.759854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba7b899a323'
down_revision = 'a65a3a0c1931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('image_capture', sa.LargeBinary(length=4294967295), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'image_capture')
    # ### end Alembic commands ###
